#!/usr/bin/perl

# $Id: count_runtime_tables 313 2007-10-23 16:55:06Z duncan $
#
# Copyright (C) 2003-2012 Opsview Limited. All rights reserved
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Opsview; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

use warnings;
use strict;
use Carp;
use lib "/usr/local/nagios/perl/lib";
use lib "/usr/local/nagios/lib";
use lib "/usr/local/nagios/etc";
use Odw;

my $dbh = Odw->db_Main;

my %table_datetime_column = (
    events                              => 'datetime',
    servicecheck_results                => 'start_datetime',
    performance_data                    => 'datetime',
    state_history                       => 'datetime',
    downtime_host_history               => 'actual_start_datetime',
    downtime_service_history            => 'actual_start_datetime',
    acknowledgement_host                => 'entry_datetime',
    acknowledgement_service             => 'entry_datetime',
    notification_host_history           => 'entry_datetime',
    notification_service_history        => 'entry_datetime',
    service_outages                     => 'start_datetime',
    service_availability_hourly_summary => 'start_datetime',
);

my $sql;

foreach my $table ( keys(%table_datetime_column) ) {
    $sql = "SELECT $table_datetime_column{ $table } FROM $table ORDER BY $table_datetime_column{ $table } LIMIT 1";

    print("$sql;\n");

    my $oldest_date_ref = $dbh->selectall_arrayref($sql) || croak( $dbh->errstr );

    #use Data::Dump qw(dump);
    #print dump($oldest_date_ref);

    if ( $oldest_date_ref->[0] ) {
        print $oldest_date_ref->[0]->[0], $/;
    }
}
